import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: 'Dashboard', iconSrc: "/icon-dashboard.svg" },
  { name: 'Launchpad', iconSrc: "/icon-launchpad.svg" },
  { name: 'Payments', iconSrc: "/icon-payments.svg" },
  { name: 'Messages', iconSrc: "/icon-messages.svg" },
  { name: 'Tasks', iconSrc: "/icon-tasks.svg" },
  { name: 'Balances', iconSrc: "/icon-balances.svg" },
  { name: 'Clients', iconSrc: "/icon-clients.svg" },
  { name: 'Inbox', iconSrc: "/icon-inbox.svg" },
  { name: 'Tax Strategies', iconSrc: "icon-tax.svg" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="min-h-screen flex blueBackground">
          {/* Sidebar */}
          <aside className="w-52 text-white px-4 py-6">
            <div className="font-bold py-2 rounded-lg text-lg mb-6">
              <Image src="dime-logo.svg" alt="Dime logo" height="24" width="89" />
            </div>
            <nav className="flex flex-col gap-3">
              {
                navItems.map((item) => (
                  <div
                    key={item.name}
                    className={"px-3 py-2 flex gap-2 items-center rounded cursor-pointer dimeMenuSelector"}
                  >
                    <Image src={item.iconSrc} alt="Dime logo" height="16" width="16" />
                    <span className={`text-sm text-dimeFieldGrey ${item.name === 'Clients' ? 'dimeWarmYellow' : '' }`}>{item.name}</span>
                  </div>
                ))}
          </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 bg-[#f4f5f7] p-6 mr-4 mt-6 rounded-t-2xl">{children}</main>
      </section>
    </body>
    </html >
  );
}
