import Image from "next/image";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";


import "./globals.css";


const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: 'Dashboard', iconSrc: "/icon-dashboard.svg" },
  { name: 'Launchpad', iconSrc: "/icon-launchpad.svg" },
  { name: 'Payments', iconSrc: "/icon-payments.svg" },
  { name: 'Messages', iconSrc: "/icon-messages.svg" },
  { name: 'Tasks', iconSrc: "/icon-tasks.svg" },
  { name: 'Balances', iconSrc: "/icon-balances.svg" },
  { name: 'Clients', iconSrc: "/icon-clients.svg" },
  { name: 'Inbox', iconSrc: "/icon-inbox.svg" },
  { name: 'Tax Strategies', iconSrc: "icon-tax.svg" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <section className="min-h-screen flex gredientBackground">
          {/* Sidebar */}
          <aside className="flex flex-col justify-between w-52 text-white px-4 py-6">
            <div>
              <div className="font-bold py-2 rounded-lg text-lg mb-6">
                <Image src="dime-logo.svg" alt="Dime logo" height="24" width="90" />
              </div>
              <nav className="flex flex-col gap-3">
                {
                  navItems.map((item) => (
                    <div
                      key={item.name}
                      className={"px-3 py-2 flex gap-2 items-center rounded cursor-pointer hover:bg-menu-selector"}
                    >
                      <Image src={item.iconSrc} alt="Dime logo" height="16" width="16" />
                      <span className={`text-sm text-field-grey ${item.name === 'Clients' ? 'text-warm-yellow' : ''}`}>{item.name}</span>
                    </div>
                  ))}
              </nav>
            </div>
            <div className="flex flex-col gap-4">
              <span>Unlock Navabar</span>
              <span>Launchpad</span>
              <span>Settings</span>
              <span>User Profile</span>
            </div>




          </aside>

          {/* Main Content */}
          <main className="flex-1 bg-[#f4f5f7] p-6 mr-4 mt-6 rounded-t-2xl">{children}</main>
        </section>
      </body>
    </html >
  );
}
